### ISSUE TITLE
Possibility to order feeds in a specific/personal order

### ISSUE THREAD

**Issue by sn-o-w** [synzen/MonitoRSS#175]
**Is your feature request related to a problem? Please describe.**
When you have a lots of feeds, it's kinda hard to remove and re-add every feed just to make sure they are in a specific/personal order (not to mention when you even have filters or other feed(s) custom options/things). It could help people to have a better overview over their feeds.

**Describe the solution you'd like**
The option to order feeds via web UI, perhaps a command as well (like rss.order or rss.setorder)

**Comment by synzen** [comment]
Thanks for the suggestion. It seems your problem is mostly aesthetics (which is understandable). Something like this is unfortunately not trivial (in terms of implementation and user interaction), so it will be on the back burner for now due to more urgent issues (with rate limiting). If enough people have strong opinions on this then I can escalate its priority. I'll leave this open until then.
