### ISSUE TITLE
[QUESTION|BUG] Connected Timed Out

### ISSUE THREAD

**Issue by BlackYuzia** [synzen/MonitoRSS#203]
Have a question or I should call this is a bug?

If I check in web rss feed, I successfuly get info about rss.
I get title, link and etc.

Example:
![image](https://user-images.githubusercontent.com/25010528/111203577-ddbef000-85cd-11eb-9265-17b15c6e3111.png)

I try add my rss link by using bot, but I get error:
![image](https://user-images.githubusercontent.com/25010528/111203665-f6c7a100-85cd-11eb-8186-f05aab064e60.png)

I try the same with website, I success add this, list:
![image](https://user-images.githubusercontent.com/25010528/111203754-0cd56180-85ce-11eb-8506-508ec90c5196.png)

But, when I try `test` now, I get error, the same like in last time:
![image](https://user-images.githubusercontent.com/25010528/111203804-1fe83180-85ce-11eb-9d0f-31cdf7209306.png)

When I press `send  original message` on website, bot successfully send message:
![image](https://user-images.githubusercontent.com/25010528/111204301-ac92ef80-85ce-11eb-8169-49cd96db21d2.png)

RSS LINK: `https://mangadex.org/rss/FEevGAmbVwxcBaKpyMsnRk5gfS29CDYT/manga_id/43692?h=0`

**Comment by synzen** [comment]
Hi, for the public host, the bot and web are hosted on two different servers, so they aren't guaranteed to have the same issues.

If the feed connection times out, then unfortunately the site is most likely responsible for that for whatever reason. It may be something wrong on their end, or it may be that it throttles the bot, but this is generally not something that can be worked around because it's fully dependent on the feed
