### ISSUE TITLE
Discord Forum

### ISSUE THREAD

**Issue by poyumei** [synzen/MonitoRSS#340]
Right now, the bot can only post the feeds in specific channels. I hope for a feature that can post RSS feeds in a specific thread or the forum of Discord

**Comment by synzen** [comment]
This is currently possible on personal feeds on the public bot, but unfortunately I have yet to document the way to self-host the newer versions of the code. Feature development on legacy feeds will no longer happen since personal feeds will replace them.

Until the documentation is complete, if you'd like to try targeting forum channels, you may try using the public bot https://discord.com/oauth2/authorize?client_id=268478587651358721&scope=bot
