### ISSUE TITLE
How to deploy the bot only?

### ISSUE THREAD

**Issue by Kisaragi-ng** [synzen/MonitoRSS#368]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

I noticed https://github.com/synzen/MonitoRSS-Clone has been archived and it's recommended to use this repository instead. however, I feel like what we have here is way too excessive for my needs.

> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.

If possible, there's a documentation for minimal deployment that only include the core of the bot + mongodb container.

> **Additional context**
> Add any other context or screenshots about the feature request here.

this is the resources used from MonitoRSS-Clone
![old](https://github.com/synzen/MonitoRSS/assets/88741696/623007b4-a241-4031-91f2-42dcd9526d7c)
and this is resources used in this MonitoRSS
![image](https://github.com/synzen/MonitoRSS/assets/88741696/04df6d06-8dde-4ae3-8e94-baaff02d9ca3)
which is quite steep differences. I'd also like to mention that my old machine/vps can't even build the one in this MonitoRSS repo.

while I understand `@synzen` has to take care of scaling due to numbers of users & feeds that need to get sent, I think most of us that self-host mostly doesn't need this feature.
personally, my reason to self host is that I have to use certain rss sources that I don't feel comfortable to put it in the public instances (due to local domain names, keys .etc) and having the bot with only discord command is enough.

**Comment by synzen** [comment]
Thanks for providing the description and context of your problem.

I would think of scalability as less of a feature, and more of a way the application is/has been forced to be architected because of usage. With this in mind, I understand the concerns but those containers are vital to the bot functions (minus two which is legacy-feed-bulk-converter-service if you have no legacy feeds to convert, and bot-presence-service if you don't care about the bot's online status)

Previously, all of its critical functions were being handled within a single process which unfortunately doesn't scale. Its various functions had to be splintered into multiple services, hence the multiple containers - the "core" of the bot are these services.

Additionally:
- If you force docker compose to only build one container at the time, this usually allows all the containers to build even on low-spec machines. 
- Discord commands are no longer supported due Discord's forced privileged intent migration, and the complexity of the customization that makes slash commands insufficient/too proprietary to support

**Comment by Kisaragi-ng** [comment]
Hi Synzen, appreciate your response.

Unfortunately, the new system doesn't suit my use case. In the future, I'll use Flexget instead.
For anyone facing a similar issue and looking for alternative, here's the gist: [4f2df9a2](https://gist.github.com/Kisaragi-ng/4f2df9a2e25ff414cf66d301883993cb)

Thanks for your dedication to this project.
