### ISSUE TITLE
html to markdown: The `*` character is not escaped

### ISSUE THREAD

**Issue by m417z** [synzen/MonitoRSS#376]
**Feed URL**
https://mods.windhawk.net/updates.atom

**Describe the issue**
I have a feed item with HTML content similar to:
```html
Some text '*' some more text <code>C:\Programs\Firefox-Version-*\firefox.exe</code>.
```

When converting to markdown, the result should be similar to:
```markdown
Some text '\*' some more text `C:\Programs\Firefox-Version-*\firefox.exe`.
```

But the `*` character isn't escaped and so instead of:
> Some text '\*' some more text `C:\Programs\Firefox-Version-*\firefox.exe`.

The result is:
> Some text '*' some more text \`C:\Programs\Firefox-Version-*\firefox.exe`.

**Screenshots**
![image](https://github.com/synzen/MonitoRSS/assets/4129781/fbf39c92-017a-438d-837b-4df6f78ae178)

**Branch (please specify one):**
public bot

**Comment by synzen** [comment]
Apologies for the late response. I believe, at this time, this issue may be better suited to be resolved by custom placeholders since escaping markdown characters may be tricky/pose more problems than it solves given that those characters may also be in URLs in the article content. If you use custom placeholders with the below configuration:

![image](https://github.com/synzen/MonitoRSS/assets/18688793/fe08bff6-97ee-4f03-9a99-ee76d0ac6445)

This should resolve the issue

**Comment by m417z** [comment]
Thanks. I think it's the html to markdown functionality's responsibility to do the correct conversion, but it's up to you. As you mentioned, managing it manually is error prone.
